test:
  clients:
    default:
      database: omega_customer_support_portal_api_test
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false

development:
  clients:
    default:
      database: omega_customer_support_portal_api_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false


staging:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
  options:
    raise_not_found_error: false


production:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
  options:
    raise_not_found_error: false

