# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 287a88f2d78cb047bc97d2b973f4e71c1ada8e7fb8c934b2446ca48062687f003d9cad265063c7edceb2faa780910f4854c671046a1ca20d3d64e5045a56051b

test:
  secret_key_base: acc79048a9f9bf34c02372fe57535c79ca8729fe12bff3672572256c83882a34194352d6ee01c9ae81555daa5b33437de89a01df7e05daab47562782d00869ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
